server:
  port: 8084

spring:
  application:
    name: decor-house
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/decor_house_prod?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
